### ISSUE TITLE
Stopped Working?

### ISSUE THREAD

**Issue by emule** [todhm/sd_feed#13]
Not loading anymore for me, working for you?
I reinstalled but the problem persists, I did not identify any errors in loading Stable Diffusion.
![noerror](https://github.com/todhm/sd_feed/assets/1180638/576a3878-ef8e-40ea-a47d-8f32d237c87c)

**Comment by voxefx** [comment]
same issue.

**Comment by BroctorDF** [comment]
same hare, it's been two days since its down.

**Comment by DuckersMcQuack** [comment]
Same. Here's the error from automatic for author. Reply if more info/logs if it made is needed.  

Traceback (most recent call last):
      File "H:\Stablediff\Automatic1111\WebuiDuckers\webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "H:\Stablediff\Automatic1111\WebuiDuckers\webui\extensions\sd_feed\newtype_v3\newtype_v3.py", line 45, in search_lora
        searched_list = [
    TypeError: 'bool' object is not iterable

**Comment by VelvetAcidChrist** [comment]
On the main feed site, where all the images come from, all the content is gone too, and now it's empty

**Comment by PatrickJnr** [comment]
So this is dead now?

**Comment by KaizerHanz** [comment]
yeah same issues, I need this to find lora, anyone know how to find lora? I'm searching on civitai but no luck

**Comment by Devicetron** [comment]
did anyone make a copy off all those images? maybe some chinese backup site?
