### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sunhunter202** [todhm/sd_feed#4]
Error running after_component: C:\stable-diffusion-webui\extensions\sd_feed\scripts\main.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 470, in after_component
    script.after_component(component, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd_feed\newtype_v3\newtype_v3.py", line 123, in after_component
    gr.HTML(f.read(), elem_id="feed-profile-tab")
UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 1070: illegal multibyte sequence

Error running after_component: C:\stable-diffusion-webui\extensions\sd_feed\scripts\main.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 470, in after_component
    script.after_component(component, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd_feed\newtype_v3\newtype_v3.py", line 110, in after_component
    f.read(),
UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 39: illegal multibyte sequence

Error executing callback ui_tabs_callback for C:\stable-diffusion-webui\extensions\sd_feed\scripts\main.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "C:\stable-diffusion-webui\extensions\sd_feed\newtype_v3\tabs\feed.py", line 22, in on_ui_tabs
    gr.HTML(f.read(), elem_id="vue-elem")
UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 3014: illegal multibyte sequence

**Comment by todhm** [comment]
We update new version to resolve this and I will close this issue
